import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar/Navbar";
import Footer from "@/components/ui/Footer/Footer";
import { ApiProvider } from "@/framework/shopify";
import { SheetProvider } from "@/components/Product/SheetContext/SheetContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApiProvider>
          <SheetProvider>
            <Navbar />
            {children}
            <Footer />
          </SheetProvider>
        </ApiProvider>
      </body>
    </html>
  );
}
